const DATA_PATHS=['data/resources.json','data/additional-resources.json','data/research-resources.json','data/urdu-south-asia-resources.json','data/expansion-batch-01.json','data/expansion-batch-02.json','data/expansion-batch-03.json'];
const esc=(s='')=>s.replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const quality=(r)=>{const b=[];if(r.verified)b.push('<span class="quality-badge verified">✓ Verified</span>');if(r.official)b.push('<span class="quality-badge official">Official</span>');if(r.free)b.push('<span class="quality-badge free">Free</span>');return b.join('')};
function card(r){return `<article class="resource-card"><div class="resource-meta"><span class="badge">${esc(r.type)}</span><span class="tag">${esc((r.languages||[]).join(' · '))}</span></div>${quality(r)?`<div class="quality-row">${quality(r)}</div>`:''}<h3>${esc(r.name)}</h3><p>${esc(r.description)}</p><div class="tags">${(r.categories||[]).slice(0,3).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><a class="resource-link" href="resource.html?id=${encodeURIComponent(r.id)}">Details →</a></article>`}
const resourceDate=r=>r.addedAt||r.dateAdded||r.updatedAt||null;
const loadJson=async p=>fetch(p).then(r=>r.ok?r.json():[]).catch(()=>[]);
async function getResources(){const [sets,qualityData]=await Promise.all([Promise.all(DATA_PATHS.map(loadJson)),loadJson('data/quality.json')]);const q=new Map(qualityData.map(x=>[x.id,x]));const seen=new Set();return sets.flat().filter(r=>{if(!r||!r.id||seen.has(r.id))return false;seen.add(r.id);return true}).map(r=>({...r,...(q.get(r.id)||{})}))}
async function load(){try{const resources=await getResources();const featured=document.querySelector('#featuredGrid');if(featured){const selected=resources.filter(r=>r.featured||r.verified).slice(0,8);featured.innerHTML=selected.length?selected.map(card).join(''):'<div class="empty">Featured resources are being curated.</div>'}const count=document.querySelector('#resourceCount');if(count)count.textContent=`${resources.length}`;const categoryCount=document.querySelector('#categoryCount');if(categoryCount)categoryCount.textContent=`${new Set(resources.flatMap(r=>r.categories||[])).size}`;const languageCount=document.querySelector('#languageCount');if(languageCount)languageCount.textContent=`${new Set(resources.flatMap(r=>r.languages||[])).size}`;const recent=document.querySelector('#recentGrid');if(recent){const dated=resources.filter(r=>resourceDate(r)).sort((a,b)=>new Date(resourceDate(b))-new Date(resourceDate(a)));const selected=(dated.length?dated:resources).slice(0,6);recent.innerHTML=selected.length?selected.map(card).join(''):'<div class="empty">Resources are being curated.</div>'}const collectionGrid=document.querySelector('#homeCollectionGrid');if(collectionGrid){const icons={'start-here':'🧭','urdu-south-asia':'🌐','kids-families':'👨‍👩‍👧','research':'🔬','fiqh-practical':'⚖️','duas-ziyarat':'🤲','youth-english':'🎓'};const collections=await loadJson('data/collections-v2.json');collectionGrid.innerHTML=collections.length?collections.slice(0,3).map(c=>`<a class="collection-card" href="resources.html?search=${encodeURIComponent(c.search||c.category||'')}"><span aria-hidden="true">${icons[c.id]||'✦'}</span><h2>${esc(c.title)}</h2><p>${esc(c.description)}</p><b>Explore →</b></a>`).join(''):'<div class="empty">Collections could not be loaded right now. <a href="collections.html">Browse collections →</a></div>'}const input=document.querySelector('#searchInput');const clear=document.querySelector('#clearSearch');if(input){const go=q=>{const value=q.trim();if(value)window.location.href=`resources.html?search=${encodeURIComponent(value)}`};input.addEventListener('keydown',e=>{if(e.key==='Enter')go(input.value)});clear?.addEventListener('click',()=>{input.value='';input.focus()});document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.query;go(input.value)}));}}catch(e){console.error('Could not load resources',e)}}
document.addEventListener('DOMContentLoaded',load);
