const escV=(s='')=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const levels={official:'Official source',recognized:'Recognized educational source','scholar-linked':'Scholar-linked',community:'Community source',unknown:'Source not yet assessed'};
const topicFilters=[['Prayer','🕌 Namaz'],['Quran','📖 Quran'],['Ahlulbayt','💚 Ahlulbayt'],['Imam Mahdi','🌙 Imam Mahdi'],['Karbala','🏴 Karbala'],['Duas','🤲 Duas'],['Stories','📚 Stories'],['Nasheeds','🎵 Nasheeds'],['Islamic values','🌱 Values']];
let allVideos=[];let activeAge='all';let activeLang='all';let activeKind='all';let activeTopic='all';
const curatedKids=[];
function isUrdu(v){return (v.languages||[]).some(x=>x.toLowerCase()==='urdu')}
function scoreStart(v,age){let s=0;if((v.ageRange||[]).includes(age))s+=6;if(isUrdu(v))s+=5;if(v.free)s+=2;if(v.featured)s+=2;if(v.kind==='series')s+=1;return s}
function card(v){const age=(v.ageRange||[]).join(' · ');const source=levels[v.sourceLevel]||levels.unknown;return `<article class="resource-card"><div class="resource-meta"><span class="badge">${escV(v.type||'Video')}</span><span class="tag">${escV((v.languages||[]).join(' · '))}</span></div><div class="quality-row"><span class="quality-badge source-level ${escV(v.sourceLevel||'unknown')}">${escV(source)}</span>${v.free?'<span class="quality-badge free">Free</span>':''}</div><h3>${escV(v.name)}</h3><p>${escV(v.description)}</p><div class="fit-note"><strong>Channel / series context</strong><ul><li>${escV(v.channel||v.name||'Source not specified')}</li><li>${escV(v.series||v.type||'Individual video')}</li>${v.parentNote?`<li>${escV(v.parentNote)}</li>`:''}</ul></div><div class="tags">${age?`<span class="tag">Ages ${escV(age)}</span>`:''}${(v.categories||[]).slice(0,4).map(x=>`<span class="tag">${escV(x)}</span>`).join('')}</div><div class="card-actions"><a class="resource-link" href="${escV(v.url)}" target="_blank" rel="noopener noreferrer">Watch / Explore →</a></div></article>`}
function filtered(){return allVideos.filter(v=>activeAge==='all'||(v.ageRange||[]).includes(activeAge)).filter(v=>activeLang==='all'||(v.languages||[]).some(x=>x.toLowerCase()===activeLang.toLowerCase())).filter(v=>activeKind==='all'||(activeKind==='channel'?(v.channel===true||v.kind==='channel'||String(v.type||'').toLowerCase().includes('channel')||String(v.type||'').toLowerCase().includes('platform')):(v.kind===activeKind||String(v.type||'').toLowerCase().includes(activeKind)))).filter(v=>activeTopic==='all'||(v.categories||[]).some(x=>x.toLowerCase()===activeTopic.toLowerCase())||(v.tags||[]).some(x=>x.toLowerCase()===activeTopic.toLowerCase()))}
function render(){let list=filtered();document.getElementById('videoCount').textContent=`${list.length} curated video resources`;document.getElementById('videoGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">No videos match these filters yet.</div>'}
function renderStartCards(age){const box=document.querySelector('.start-here-grid');if(!box)return;const picks=allVideos.filter(v=>(v.ageRange||[]).includes(age)).sort((a,b)=>scoreStart(b,age)-scoreStart(a,age)).slice(0,3);box.innerHTML=picks.length?picks.map(v=>`<article class="start-pick">${card(v)}</article>`).join(''):`<div class="empty">No curated picks for this age yet.</div>`}
function injectTopicFilters(){const box=document.querySelector('.video-filters');if(!box)return;topicFilters.forEach(([topic,label])=>{if(box.querySelector(`[data-topic="${CSS.escape(topic)}"]`))return;const b=document.createElement('button');b.type='button';b.className='filter-btn';b.dataset.topic=topic;b.textContent=label;box.appendChild(b);b.onclick=()=>{document.querySelectorAll('.video-filters .filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeAge='all';activeLang='all';activeKind='all';activeTopic=topic;render()}})}
function injectStartHere(){const grid=document.getElementById('videoGrid');if(!grid||document.querySelector('.start-here'))return;const wrap=document.createElement('section');wrap.className='start-here';wrap.innerHTML=`<div class="start-here-head"><div><p class="eyebrow">For parents</p><h2>Start here — Urdu-friendly picks first</h2><p>These shortcuts prioritize Urdu-friendly resources where available, while keeping age suitability and source context visible.</p></div></div><div class="start-here-grid"><button type="button" class="start-age" data-start-age="3–5"><span>👶</span><strong>Ages 3–5</strong><small>Stories, simple duas & nasheeds</small></button><button type="button" class="start-age" data-start-age="6–8"><span>🧒</span><strong>Ages 6–8</strong><small>Quran stories, Namaz & Ahlulbayt</small></button><button type="button" class="start-age" data-start-age="9–12"><span>👦</span><strong>Ages 9–12</strong><small>Karbala, Imam Mahdi & values</small></button></div></section>`;grid.parentNode.insertBefore(wrap,grid);wrap.querySelectorAll('.start-age').forEach(b=>b.onclick=()=>{activeAge=b.dataset.startAge;activeLang='all';activeKind='all';activeTopic='all';document.querySelectorAll('.video-filters .filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderStartCards(activeAge);document.querySelector('.start-here').scrollIntoView({behavior:'smooth',block:'start'})})}
async function injectShiaKidsChannels(){if(document.querySelector('.shia-kids-channels'))return;const anchor=document.getElementById('videoGrid')?.closest('.section');if(!anchor)return;const section=document.createElement('section');section.className='section soft shia-kids-channels';section.innerHTML=`<div class="container"><div class="section-heading"><div><p class="eyebrow">Direct access for children</p><h2>Shia Kids Channels</h2><p>Open child/family-focused Shia channels and platforms directly, with age and language shown before you leave the hub.</p></div></div><div class="video-browse-grid" id="shiaKidsChannelGrid"><div class="empty">Loading channels…</div></div></div>`;anchor.after(section);try{const data=await fetch('data/shia-kids-channels.json').then(r=>r.ok?r.json():[]);const box=section.querySelector('#shiaKidsChannelGrid');box.innerHTML=data.map(v=>`<a class="video-browse-card" href="${escV(v.url)}" target="_blank" rel="noopener noreferrer"><span>📺</span><strong>${escV(v.name)}</strong><small>${escV(v.type)} · Ages ${escV(v.age)}</small><small>${escV(v.language)}</small><small>${escV(v.focus)}</small>${v.free?'<span class="quality-badge free">Free</span>':''}</a>`).join('')||'<div class="empty">No channels available yet.</div>'}catch(e){section.querySelector('#shiaKidsChannelGrid').innerHTML='<div class="empty">Channels could not be loaded right now.</div>'}}
document.addEventListener('DOMContentLoaded',async()=>{const [external,urdu]=await Promise.all([fetch('data/kids-video-resources.json').then(r=>r.ok?r.json():[]).catch(()=>[]),fetch('data/urdu-kids-videos.json').then(r=>r.ok?r.json():[]).catch(()=>[])]);allVideos=[...curatedKids,...external,...urdu].filter((v,i,a)=>a.findIndex(x=>x.id===v.id)===i);document.querySelectorAll('.video-filters .filter-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.video-filters .filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeAge=b.dataset.age||'all';activeLang=b.dataset.lang||'all';activeKind=b.dataset.kind||'all';activeTopic=b.dataset.topic||'all';render()});injectTopicFilters();injectStartHere();render();injectShiaKidsChannels()});