const escV=(s='')=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const levels={official:'Official source',recognized:'Recognized educational source','scholar-linked':'Scholar-linked',community:'Community source',unknown:'Source not yet assessed'};
let allVideos=[];let activeAge='all';let activeLang='all';
const curatedKids=[
{id:'kids-ahlulbayt-kids',name:'Ahlulbayt Kids',type:'YouTube channel',description:'Shia Islamic kids channel with animated material including Shia prayer, tayammum and Quran/Ahlulbayt learning.',url:'https://www.youtube.com/@ahlulbaytkids',channel:'Ahlulbayt Kids',series:'Kids animation / prayer learning',languages:['Urdu','English'],ageRange:['6–8','9–12'],categories:['Kids','Prayer','Quran','Ahlulbayt'],sourceLevel:'community',free:true,parentNote:'Channel-level suitability does not mean every upload is approved; preview individual videos when needed.'},
{id:'kids-hujja-kids',name:'Hujja Kids',type:'Kids platform',description:'Shia Islamic educational and entertainment platform for children, with age-appropriate shows, interactive programs and activities.',url:'https://hujjakids.com/',channel:'Hujja Kids',series:'Shows and interactive programs',languages:['English'],ageRange:['3–5','6–8','9–12'],categories:['Kids','Stories','Learning','Imam Mahdi'],sourceLevel:'scholar-linked',free:false,parentNote:'The platform describes its content as age-appropriate and states scholar approval on its website; parents should still choose individual content appropriately.'},
{id:'kids-faraj-jawad-maahira',name:'Faraj Kids — Jawad & Maahira',type:'Kids video series',description:'Children’s videos and nasheeds presenting Quran and Ahlulbayt teachings in an engaging format, including Urdu-dubbed material.',url:'https://www.farajkids.org/videos/jawad-maahira/',channel:'Faraj Kids',series:'Jawad & Maahira',languages:['Urdu','English'],ageRange:['6–8','9–12'],categories:['Kids','Stories','Nasheeds','Karbala'],sourceLevel:'community',free:true,parentNote:'Useful starting point for Urdu-speaking families; review individual videos for age and sensitivity.'},
{id:'kids-ahlbyt-kids',name:'Ahlbyt KIDS',type:'Kids video platform',description:'Shia-focused children’s video space presenting cartoons, stories, nasheeds and Islamic learning material.',url:'https://ahlbyt.com/',channel:'Ahlbyt KIDS',series:'Kids cartoons, stories and nasheeds',languages:['English'],ageRange:['3–5','6–8','9–12'],categories:['Kids','Stories','Nasheeds','Cartoons'],sourceLevel:'community',free:false,parentNote:'The service describes itself as ad-free and curated from Shia creators; access terms may apply.'}
];
function card(v){const age=(v.ageRange||[]).join(' · ');const source=levels[v.sourceLevel]||levels.unknown;return `<article class="resource-card"><div class="resource-meta"><span class="badge">${escV(v.type)}</span><span class="tag">${escV((v.languages||[]).join(' · '))}</span></div><div class="quality-row"><span class="quality-badge source-level ${escV(v.sourceLevel||'unknown')}">${escV(source)}</span>${v.free?'<span class="quality-badge free">Free</span>':''}</div><h3>${escV(v.name)}</h3><p>${escV(v.description)}</p><div class="fit-note"><strong>Channel / series context</strong><ul><li>${escV(v.channel||'Channel not specified')}</li><li>${escV(v.series||'Individual video')}</li>${v.parentNote?`<li>${escV(v.parentNote)}</li>`:''}</ul></div><div class="tags">${age?`<span class="tag">Ages ${escV(age)}</span>`:''}${(v.categories||[]).slice(0,3).map(x=>`<span class="tag">${escV(x)}</span>`).join('')}</div><div class="card-actions"><a class="resource-link" href="${escV(v.url)}" target="_blank" rel="noopener noreferrer">Watch / Explore →</a></div></article>`}
function render(){let list=allVideos.filter(v=>activeAge==='all'||(v.ageRange||[]).includes(activeAge)).filter(v=>activeLang==='all'||(v.languages||[]).some(x=>x.toLowerCase()===activeLang.toLowerCase()));document.getElementById('videoCount').textContent=`${list.length} curated video resources`;document.getElementById('videoGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty">No videos match this age/language yet.</div>'}
document.addEventListener('DOMContentLoaded',async()=>{const external=await fetch('data/kids-video-resources.json').then(r=>r.ok?r.json():[]).catch(()=>[]);allVideos=[...curatedKids,...external.filter(v=>!curatedKids.some(c=>c.id===v.id))];document.querySelectorAll('.video-filters .filter-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.video-filters .filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeAge=b.dataset.age||'all';activeLang=b.dataset.lang||'all';if(b.dataset.lang)activeAge='all';render()});render()});